### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [4]:
import numpy as np
import matplotlib.pyplot as plt
import random

In [5]:
random.uniform (0,1)

0.2937880213683488

In [7]:
# vector = [random.uniform(0, 1) for _ in range(10)]

Вектор: [0.1482872538576031, 0.879663045171619, 0.28977985266653505, 0.5300343281106443, 0.07003692043579335, 0.6911408068728384, 0.9489888881675895, 0.8328905378308451, 0.7610470803365338, 0.08707280289088626]


In [25]:
vector = np.random.rand(1,10)
print("Вектор:", vector)

Вектор: [[0.2601817  0.90039006 0.82921028 0.57071444 0.42355406 0.88616392
  0.56372146 0.23539956 0.24402536 0.47723528]]


In [13]:
vector.shape

(1, 10)

In [16]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
print("Матриця:")
print(matrix)

Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]


In [17]:
matrix.shape

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [34]:
# Можна було залишити vector, якщо нам потрібно оновити саме ці дані.
vector_a = (vector + 10).round(2)
vector_a

array([[10.26, 10.9 , 10.83, 10.57, 10.42, 10.89, 10.56, 10.24, 10.24,
        10.48]])

In [29]:
matrix_a = matrix * 2
matrix_a

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [33]:
# Можна було використати vector_a, якщо нам потрібні були нові дані.
vector_b = vector**2
vector_b

array([[0.06769452, 0.81070227, 0.68758969, 0.32571497, 0.17939804,
        0.78528649, 0.31778189, 0.05541295, 0.05954838, 0.22775351]])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [36]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [38]:
result_matrix = np.dot (A.T, B.T)
result_matrix

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [45]:
matrix_2 = np.dot (result_matrix, C)
matrix_2

array([[0.2034],
       [0.2846]])

In [52]:
matrix_2.shape

(2, 1)

In [49]:
matrix_3 = np.dot (result_matrix, D)
matrix_3

array([[0.2034, 0.7281],
       [0.2846, 0.5202]])

In [51]:
matrix_3.shape

(2, 2)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [53]:
result_matrix.T

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [78]:
vector_t = vector.T

In [79]:
vector_t.shape

(10, 1)

Зміна: вектор-рядок став вектором-колонкою

In [80]:
column_vector = np.expand_dims(vector_t, axis=1)
column_vector

array([[[0.2601817 ]],

       [[0.90039006]],

       [[0.82921028]],

       [[0.57071444]],

       [[0.42355406]],

       [[0.88616392]],

       [[0.56372146]],

       [[0.23539956]],

       [[0.24402536]],

       [[0.47723528]]])

In [81]:
column_vector.shape

(10, 1, 1)

###### Ця операція додала нову ось до вашого масиву.
column_vector має розмірність (10, 1, 1). Це означає:

Перша ось: 10 елементів.
Друга ось: 1 елемент у кожному "блоці".
Третя ось: 1 значення всередині кожного блоку.

In [82]:
column_vector.T

array([[[0.2601817 , 0.90039006, 0.82921028, 0.57071444, 0.42355406,
         0.88616392, 0.56372146, 0.23539956, 0.24402536, 0.47723528]]])

In [84]:
column_vector.T.shape

(1, 1, 10)

In [86]:
#transposed = np.transpose(column_vector)
#transposed

array([[[0.2601817 , 0.90039006, 0.82921028, 0.57071444, 0.42355406,
         0.88616392, 0.56372146, 0.23539956, 0.24402536, 0.47723528]]])